# Generated by Django 5.1.1 on 2024-11-08 11:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('STAND_UP_APP', '0002_user_lieu'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='Age',
        ),
    ]
