# Generated by Django 5.1.1 on 2024-11-10 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('STAND_UP_APP', '0003_remove_user_age'),
    ]

    operations = [
        migrations.AddField(
            model_name='alerte',
            name='Dates',
            field=models.DateField(auto_now=True),
        ),
    ]
