# Generated by Django 5.1.1 on 2024-11-10 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('STAND_UP_APP', '0004_alerte_dates'),
    ]

    operations = [
        migrations.AddField(
            model_name='alerte',
            name='Photo',
            field=models.ImageField(blank=True, upload_to='Images/'),
        ),
    ]
