# Generated by Django 5.1.1 on 2024-11-11 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('STAND_UP_APP', '0005_alerte_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='Etat_civil',
            field=models.CharField(default='Célibataire', max_length=100),
        ),
    ]
