# Generated by Django 5.1.1 on 2024-11-11 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('STAND_UP_APP', '0006_user_etat_civil'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='Dates',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
