# Generated by Django 5.1.1 on 2024-11-11 09:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('STAND_UP_APP', '0008_alter_alerte_dates'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alerte',
            name='Air_de_sante',
        ),
    ]
