# Generated by Django 5.1.1 on 2024-11-11 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('STAND_UP_APP', '0009_remove_alerte_air_de_sante'),
    ]

    operations = [
        migrations.CreateModel(
            name='Organisation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nom', models.CharField(max_length=500)),
                ('Adresse', models.CharField(max_length=500)),
                ('Tel', models.CharField(max_length=200)),
            ],
        ),
    ]
