# Generated by Django 5.1.1 on 2024-11-12 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('STAND_UP_APP', '0010_organisation'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='Stand_up',
            field=models.BooleanField(default='False'),
        ),
    ]
