# Generated by Django 5.1.1 on 2024-11-12 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('STAND_UP_APP', '0011_user_stand_up'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='Organisation',
            field=models.CharField(default='-', max_length=500),
        ),
    ]
