# Generated by Django 5.1.1 on 2024-11-12 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('STAND_UP_APP', '0012_user_organisation'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='Matricule',
            field=models.CharField(default='---', max_length=50),
        ),
    ]
