# Generated by Django 5.1.1 on 2024-11-12 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('STAND_UP_APP', '0013_user_matricule'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='Stand_up',
            field=models.BooleanField(default='True'),
        ),
    ]
