# Generated by Django 5.1.1 on 2024-11-12 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('STAND_UP_APP', '0014_alter_user_stand_up'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='Nom',
            field=models.CharField(default='-', max_length=20),
        ),
    ]
