# Generated by Django 4.2 on 2024-11-21 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('STAND_UP_APP', '0015_user_nom'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='Tel',
            field=models.CharField(default='---', max_length=50),
        ),
    ]
